apiVersion: v1
kind: Service
metadata:
  name: {{ include "bits-ws.fullname" . }}
  labels:
    {{- include "bits-ws.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "{{ include "bits-ws.fullname" . }}"}'
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bits-ws.selectorLabels" . | nindent 4 }}
